[[plugins]]
hook_add = 'source $VIM_PATH/configs/coc.vim'
merged   = 0
repo     = 'neoclide/coc.nvim'
rev      = 'release'

[[plugins]]
depends = 'coc.nvim'
if      = 'has("python3")'
merged  = 0
repo    = 'honza/vim-snippets'
