[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}

[[plugins]]
repo = 'kana/vim-niceblock'
on_map = {x = '<Plug>'}
hook_add = '''
  xmap I  <Plug>(niceblock-I)
  xmap A  <Plug>(niceblock-A)
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'
on_event = [ 'BufReadPost', 'BufWritePost' ]

[[plugins]]
repo = 'psliwka/vim-smoothie'
on_func = 'smoothie#'
hook_add = '''
  let g:smoothie_no_default_mappings = v:true
'''

[[plugins]]
repo = 'farmergreg/vim-lastplace'

[[plugins]]
repo = 'lfv89/vim-interestingwords'
if = 1

[[plugins]]
repo = 'itchyny/vim-cursorword'
if = 1

[[plugins]]
repo = 'tyru/caw.vim'
depends = 'context_filetype.vim'
on_map = { nx = '<Plug>' }

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = { n = '<Plug>' }
hook_source = '''
    let g:EasyMotion_do_mapping = 0
    let g:EasyMotion_prompt = 'Jump to → '
    let g:EasyMotion_keys = 'fjdkswbeoavn'
    let g:EasyMotion_smartcase = 1
    let g:EasyMotion_use_smartsign_us = 1
'''

[[plugins]]
repo = 'junegunn/goyo.vim'
on_cmd = 'Goyo'
hook_source = 'source $VIM_PATH/configs/goyo.vim'

[[plugins]]
repo = 'junegunn/Limelight.vim'
on_cmd = 'Limelight'
hook_add = '''
  let g:limelight_conceal_ctermfg = 'gray'
  let g:limelight_conceal_ctermfg = 240
  let g:limelight_conceal_guifg = 'DarkGray'
  let g:limelight_conceal_guifg = '#777777'
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_cmd = 'TableModeToggle'

[[plugins]]
repo = 'junegunn/vim-easy-align'
if = 1

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
  let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
'''
