[[plugins]]
on_map = { n = '<Plug>' }
repo   = 'rhysd/accelerated-jk'

[[plugins]]
hook_add = '''
  xmap I  <Plug>(niceblock-I)
  xmap A  <Plug>(niceblock-A)
'''
on_map   = { x = '<Plug>' }
repo     = 'kana/vim-niceblock'

[[plugins]]
on_event = ['BufReadPost', 'BufWritePost']
repo     = 'rhysd/clever-f.vim'

[[plugins]]
hook_add = '''
  let g:smoothie_no_default_mappings = v:true
'''
on_func  = 'smoothie#'
repo     = 'psliwka/vim-smoothie'

[[plugins]]
if   = 1
repo = 'farmergreg/vim-lastplace'

[[plugins]]
if   = 1
repo = 'lfv89/vim-interestingwords'

[[plugins]]
if   = 1
repo = 'itchyny/vim-cursorword'

[[plugins]]
depends = 'context_filetype.vim'
on_map  = { nx = '<Plug>' }
repo    = 'tyru/caw.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
hook_source = '''
    let g:EasyMotion_do_mapping = 0
    let g:EasyMotion_prompt = 'Jump to → '
    let g:EasyMotion_keys = 'fjdkswbeoavn'
    let g:EasyMotion_smartcase = 1
    let g:EasyMotion_use_smartsign_us = 1
'''
on_map      = { n = '<Plug>' }
repo        = 'easymotion/vim-easymotion'

[[plugins]]
hook_source = 'source $VIM_PATH/configs/goyo.vim'
on_cmd      = 'Goyo'
repo        = 'junegunn/goyo.vim'

[[plugins]]
hook_add = '''
  let g:limelight_conceal_ctermfg = 'gray'
  let g:limelight_conceal_ctermfg = 240
  let g:limelight_conceal_guifg = 'DarkGray'
  let g:limelight_conceal_guifg = '#777777'
'''
on_cmd   = 'Limelight'
repo     = 'junegunn/Limelight.vim'

[[plugins]]
on_cmd = 'TableModeToggle'
repo   = 'dhruvasagar/vim-table-mode'

[[plugins]]
if   = 1
repo = 'junegunn/vim-easy-align'

[[plugins]]
hook_add = '''
  let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
'''
repo     = 'editorconfig/editorconfig-vim'
