[[plugins]]
hook_post_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
  },
  textobjects = {
    select = {
      enable = true,
      keymaps = {
        ["af"] = "@function.outer",
        ["if"] = "@function.inner",
        ["ac"] = "@class.outer",
        ["ic"] = "@class.inner",
      },
    },
  },
  ensure_installed = 'all'
}
EOF
'''
on_ft            = [
  'python',
  'go',
  'javascript',
  'typescript',
  'html',
  'css',
  'rust',
  'toml',
  'lua',
  'vue',
  'yaml',
]
repo             = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
on_ft = 'toml'
repo  = 'cespare/vim-toml'

[[plugins]]
on_ft = 'jsonc'
repo  = 'neoclide/jsonc.vim'

[[plugins]]
on_ft = 'dart'
repo  = 'dart-lang/dart-vim-plugin'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
on_ft = 'requirements'
repo  = 'raimon49/requirements.txt.vim'

[[plugins]]
on_ft = 'gomod'
repo  = 'johejo/gomod.vim'

[[plugins]]
on_ft = 'kotlin'
repo  = 'udalov/kotlin-vim'
