[[plugins]]
on_ft = 'go'
repo  = 'fannheyward/go.vim'

[[plugins]]
on_ft = 'rust'
repo  = 'rust-lang/rust.vim'

[[plugins]]
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_strikethrough = 1
  let g:vim_markdown_folding_level = 6
  let g:vim_markdown_override_foldtext = 1
  let g:vim_markdown_folding_style_pythonic = 1
  let g:vim_markdown_conceal = 1
  let g:vim_markdown_conceal_code_blocks = 1
  let g:vim_markdown_new_list_item_indent = 0
  let g:vim_markdown_toc_autofit = 0
  let g:vim_markdown_edit_url_in = 'vsplit'
  let g:vim_markdown_fenced_languages = [
    \ 'c++=cpp',
    \ 'viml=vim',
    \ 'bash=sh',
    \ 'ini=dosini',
    \ 'js=javascript',
    \ 'json=javascript',
    \ 'jsx=javascriptreact',
    \ 'tsx=typescriptreact',
    \ 'docker=Dockerfile',
    \ 'makefile=make',
    \ 'py=python'
    \ ]
'''
on_ft    = 'markdown'
repo     = 'plasticboy/vim-markdown'

[[plugins]]
hook_source = '''
  let g:instant_markdown_autostart = 0
'''
on_ft       = 'markdown'
repo        = 'suan/vim-instant-markdown'
