[[plugins]]
repo = 'Shougo/dein.vim'
on_func = 'dein#'

[[plugins]]
repo = 'liuchengxu/vim-clap'
merged = 0
build = 'bash install.sh'
on_map = { n = '<Plug>' }
hook_source = 'source $VIM_PATH/configs/vim-clap.vim'

[[plugins]]
repo = 'vn-ki/coc-clap'
on_source = 'vim-clap'

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = 'MundoToggle'

[[plugins]]
repo = 'pechorin/any-jump.vim'
on_cmd = 'AnyJump'

[[plugins]]
repo = 'voldikss/vim-floaterm'
on_cmd = ['FloatermNew', 'FloatermToggle', 'FloatermPrev', 'FloatermNext', 'FloatermSend']

[[plugins]]
repo = 'liuchengxu/vista.vim'
on_cmd = ['Vista', 'Vista!', 'Vista!!']
hook_source = '''
    let g:vista#renderer#enable_icon = 1
    let g:vista_disable_statusline = 1
    let g:vista_default_executive = 'ctags'
    let g:vista_echo_cursor_strategy = 'floating_win'
    let g:vista_vimwiki_executive = 'markdown'
    let g:vista_executive_for = {
      \ 'vimwiki': 'markdown',
      \ 'pandoc': 'markdown',
      \ 'markdown': 'toc',
      \ 'yaml': 'coc',
      \ 'typescript': 'coc',
      \ 'typescriptreact': 'coc',
      \ }
'''

[[plugins]]
repo = 'ludovicchabant/vim-gutentags'
if = "executable('ctags')"
on_event = [ 'BufReadPost', 'BufWritePost' ]
hook_source = '''
  let g:gutentags_cache_dir = $DATA_PATH . '/tags'
  let g:gutentags_project_root = ['.root', '.git', '.svn', '.hg', '.project','go.mod','.Cargo.toml','tsconfig.js','jsconfig.js']
  let g:gutentags_generate_on_write = 0
  let g:gutentags_generate_on_missing = 0
  let g:gutentags_generate_on_new = 0
  let g:gutentags_exclude_filetypes = [ 'defx', 'denite', 'vista', 'magit' ]
'''

[[plugins]]
repo = 'liuchengxu/vim-which-key'
on_cmd = ['Whichkey', 'Whichkey!']
hook_add = '''
  let g:which_key_map =  { 'name' : 'Leader'}
  let g:which_key_localmap =  {'name' : 'LocalLeader'}
'''
hook_post_source = '''
  function! s:register_whichkey()
    let s:leader_key=substitute(get(g:,"mapleader","\\"), ' ', ',', '')
    let s:localleader_key= get(g:,'maplocalleader',';')
    call which_key#register(s:leader_key, 'g:which_key_map')
    call which_key#register(s:localleader_key, 'g:which_key_localmap')
  endfunction
  call s:register_whichkey()
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = [ 'G', 'Git', 'Gfetch', 'Gpush', 'Glog', 'Gclog', 'Gdiffsplit' ]
hook_source = '''
augroup user_fugitive_plugin
  autocmd!
  autocmd FileType fugitiveblame normal A
augroup END
'''

[[plugins]]
repo = 'skywind3000/asyncrun.vim'
on_cmd = 'AsyncRun'
